// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddClip(arg1) {
  return window['go']['app']['App']['AddClip'](arg1);
}

export function CleanAllUnpinned() {
  return window['go']['app']['App']['CleanAllUnpinned']();
}

export function CleanClipsOlderThan(arg1) {
  return window['go']['app']['App']['CleanClipsOlderThan'](arg1);
}

export function CleanTodayClips() {
  return window['go']['app']['App']['CleanTodayClips']();
}

export function DeleteClip(arg1) {
  return window['go']['app']['App']['DeleteClip'](arg1);
}

export function GetClips(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetClips'](arg1, arg2, arg3);
}

export function OnSecondInstanceLaunch(arg1) {
  return window['go']['app']['App']['OnSecondInstanceLaunch'](arg1);
}

export function TogglePin(arg1) {
  return window['go']['app']['App']['TogglePin'](arg1);
}

export function WriteToClipboard(arg1) {
  return window['go']['app']['App']['WriteToClipboard'](arg1);
}
