// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {options} from '../models';

export function AddClip(arg1:string):Promise<void>;

export function CleanAllUnpinned():Promise<number>;

export function CleanClipsOlderThan(arg1:number):Promise<number>;

export function CleanTodayClips():Promise<number>;

export function DeleteClip(arg1:string):Promise<void>;

export function GetClips(arg1:number,arg2:number,arg3:any):Promise<app.PaginatedClips>;

export function OnSecondInstanceLaunch(arg1:options.SecondInstanceData):Promise<void>;

export function TogglePin(arg1:string):Promise<void>;

export function UpdateClipContent(arg1:string,arg2:string):Promise<void>;

export function WriteToClipboard(arg1:string):Promise<void>;
