// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddClip(arg1) {
  return window['go']['app']['App']['AddClip'](arg1);
}

export function DeleteClip(arg1) {
  return window['go']['app']['App']['DeleteClip'](arg1);
}

export function GetClips() {
  return window['go']['app']['App']['GetClips']();
}

export function OnSecondInstanceLaunch(arg1) {
  return window['go']['app']['App']['OnSecondInstanceLaunch'](arg1);
}

export function TogglePin(arg1) {
  return window['go']['app']['App']['TogglePin'](arg1);
}

export function UpdateClipContent(arg1, arg2) {
  return window['go']['app']['App']['UpdateClipContent'](arg1, arg2);
}

export function WriteToClipboard(arg1) {
  return window['go']['app']['App']['WriteToClipboard'](arg1);
}
