// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {options} from '../models';

export function AddClip(arg1:string):Promise<void>;

export function DeleteClip(arg1:string):Promise<void>;

export function GetClips():Promise<Array<domain.Clip>>;

export function OnSecondInstanceLaunch(arg1:options.SecondInstanceData):Promise<void>;

export function TogglePin(arg1:string):Promise<void>;

export function UpdateClipContent(arg1:string,arg2:string):Promise<void>;

export function WriteToClipboard(arg1:string):Promise<void>;
